language: go

go:
  - "1.20"

before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.92.1/hugo_0.92.1_Linux-64bit.tar.gz
  - tar -xzvf hugo_0.92.1_Linux-64bit.tar.gz
  - sudo mv hugo /usr/local/bin/

install:
  - hugo version

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
